"on": issues
name: Automention Issues
jobs:
  automention:
    name: Automention
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Automention
        uses: shilman/automention@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
