name: Unit tests
"on":
  - push
jobs:
  build:
    name: Core Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: build-v2-${{ hashFiles('**/yarn.lock') }}
      - name: install, bootstrap
        run: |
          yarn bootstrap --core
      - name: test
        run: |
          yarn test --core
